version: "3"

services:
  node:
    container_name: forest-calculator
    build: .
    env_file:
      - .env
    ports:
      - "${NODE_PORT}:3000"
      - "${NODE_PORT_HTTPS}:3001"
    volumes:
      - .:/home/node/app:z
      - /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem:/etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem
    restart: unless-stopped
