version: "3.9"

services:
  node:
    container_name: forest-calculator
    build: .
    env_file:
      - .env
    ports:
      - "${NODE_PORT}:8080"
    volumes:
      - .:/home/node/app:z
    restart: unless-stopped
