version: "3"

services:
  node:
    container_name: forest-calculator
    build: .
    env_file:
      - .env
    ports:
      - "${NODE_PORT}:3000"
      - "${NODE_PORT_HTTPS}:3001"
    volumes:
      - .:/home/node/app:z
    restart: unless-stopped

